### ISSUE TITLE
Unable to integrate pc-nrfjprog-js with my electron app

### ISSUE THREAD

**Issue by baymac** [NordicSemiconductor/pc-nrfjprog-js#100]
I am getting the following error:

```
Uncaught Error: Could not locate the bindings file. Tried:
 → /home/parichay/Cypherock/cypherock-live-desktop/build/pc-nrfjprog-js.node
 → /home/parichay/Cypherock/cypherock-live-desktop/build/Debug/pc-nrfjprog-js.node
 → /home/parichay/Cypherock/cypherock-live-desktop/build/Release/pc-nrfjprog-js.node
 → /home/parichay/Cypherock/cypherock-live-desktop/out/Debug/pc-nrfjprog-js.node
 → /home/parichay/Cypherock/cypherock-live-desktop/Debug/pc-nrfjprog-js.node
 → /home/parichay/Cypherock/cypherock-live-desktop/out/Release/pc-nrfjprog-js.node
 → /home/parichay/Cypherock/cypherock-live-desktop/Release/pc-nrfjprog-js.node
 → /home/parichay/Cypherock/cypherock-live-desktop/build/default/pc-nrfjprog-js.node
 → /home/parichay/Cypherock/cypherock-live-desktop/compiled/8.9.3/linux/x64/pc-nrfjprog-js.node
 → /home/parichay/Cypherock/cypherock-live-desktop/addon-build/release/install-root/pc-nrfjprog-js.node
 → /home/parichay/Cypherock/cypherock-live-desktop/addon-build/debug/install-root/pc-nrfjprog-js.node
 → /home/parichay/Cypherock/cypherock-live-desktop/addon-build/default/install-root/pc-nrfjprog-js.node
 → /home/parichay/Cypherock/cypherock-live-desktop/lib/binding/node-v57-linux-x64/pc-nrfjprog-js.node
    at bindings (bindings.js:126)
    at Object../node_modules/pc-nrfjprog-js/index.js (index.js:38)
    at __webpack_require__ (bootstrap:724)
    at fn (bootstrap:101)
    at Object.<anonymous> (Update.js:11)
    at Object../app/components/Update.js (renderer.dev.js:2262)
    at __webpack_require__ (bootstrap:724)
    at fn (bootstrap:101)
    at Object.<anonymous> (UpdatePage.js:4)
    at Object../app/containers/UpdatePage.js (renderer.dev.js:2874)
```

For reference the source code of my electron app can be found here - https://github.com/baymac/cypherock-live-desktop/tree/test (on test branch). I need to use the following api of nrfprog:

```
nrfjprog.programDFU(
    device.serial,
    downloadLocation,
    device.path,
    15000,
    progress => {
      console.log(progress);
    },
    err => {
      if (err) throw err;
    }
  );
```

**Comment by chunfantasy** [comment]
Could you provide more info about your OS. Are you using Ubuntu 18?

**Comment by baymac** [comment]
Yes 18.04

**Comment by chunfantasy** [comment]
OK, I suggest you do the following steps for version1.6.0:
1. remove node_modules/pc-nrfjprog-js
2. npm install pc-nrfjprog-js
3. export LD_LIBRARY_PATH=path to node_modules/pc-nrfjprog-js/build/Release/
4. run the test again

If that still fails, please pin the version to 1.5.9 and let us know if the error still occurs.

**Comment by baymac** [comment]
Hi @chunfantasy, since I am using yarn I did `yarn add pc-nrfjprog-js` and set the environment variable with a `.env` file. And added pc-nrfjprog-js (both 1.6.0 and 1.5.9) to my app package but getting the following error:

```
Uncaught Error: libhighlevelnrfjprog.so: cannot open shared object file: No such file or directory
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:172:20)
    at Object.Module._extensions..node (module.js:671:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:172:20)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at bindings (/home/parichay/Cypherock/cypherock-live-desktop/app/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/home/parichay/Cypherock/cypherock-live-desktop/app/node_modules/pc-nrfjprog-js/index.js:38:37)
``` 

When tried installing in my root package.json, I got the same error as mentioned in the first comment:

```
Uncaught Error: Could not locate the bindings file. Tried:
 → /home/parichay/Cypherock/cypherock-live-desktop/build/pc-nrfjprog-js.node
 → /home/parichay/Cypherock/cypherock-live-desktop/build/Debug/pc-nrfjprog-js.node
 → /home/parichay/Cypherock/cypherock-live-desktop/build/Release/pc-nrfjprog-js.node
 → /home/parichay/Cypherock/cypherock-live-desktop/out/Debug/pc-nrfjprog-js.node
 → /home/parichay/Cypherock/cypherock-live-desktop/Debug/pc-nrfjprog-js.node
 → /home/parichay/Cypherock/cypherock-live-desktop/out/Release/pc-nrfjprog-js.node
 → /home/parichay/Cypherock/cypherock-live-desktop/Release/pc-nrfjprog-js.node
 → /home/parichay/Cypherock/cypherock-live-desktop/build/default/pc-nrfjprog-js.node
 → /home/parichay/Cypherock/cypherock-live-desktop/compiled/8.9.3/linux/x64/pc-nrfjprog-js.node
 → /home/parichay/Cypherock/cypherock-live-desktop/addon-build/release/install-root/pc-nrfjprog-js.node
 → /home/parichay/Cypherock/cypherock-live-desktop/addon-build/debug/install-root/pc-nrfjprog-js.node
 → /home/parichay/Cypherock/cypherock-live-desktop/addon-build/default/install-root/pc-nrfjprog-js.node
 → /home/parichay/Cypherock/cypherock-live-desktop/lib/binding/node-v57-linux-x64/pc-nrfjprog-js.node
    at bindings (bindings.js:126)
    at Object../node_modules/pc-nrfjprog-js/index.js (index.js:38)
    at __webpack_require__ (bootstrap:724)
    at fn (bootstrap:101)
    at Object.<anonymous> (Update.js:11)
    at Object../app/components/Update.js (renderer.dev.js:2262)
    at __webpack_require__ (bootstrap:724)
    at fn (bootstrap:101)
    at Object.<anonymous> (UpdatePage.js:4)
    at Object../app/containers/UpdatePage.js
```

Can you take look at my `package.json` and suggest if I have the right setup?

**Comment by bencefr** [comment]
Hi @baymac,

There's a change in 1.6 that the bindings library `pc-nrfjprog-js.node` is linked against `libhighlevelnrfjprog.so` as opposed to earlier behaviour in 1.5 when it loaded it runtime.

Because of this change the bindings is supposed to look for the highlevel library in `nrfjprog/` directory under the current working directory of your app. If it doesn't find it there it will fall back on `LD_LIBRARY_PATH`, so you should be able to remedy this issue by setting this environment variable to the full absolute path of the nrfjprog directory, which is located here: `node_modules/pc-nrfjprog-js/nrfjprog`.

You can test this without running your app by `ldd`. Assuming that you are in your app's directory where you also have the `node_modules`:

```
$ export LD_LIBRARY_PATH=`pwd`/node_modules/pc-nrfjprog-js/nrfjprog
$ ldd node_modules/pc-nrfjprog-js/build/Release/pc-nrfjprog-js.node
```

This will tell if the bindings is able to find the highlevel library or not.

**Comment by bencefr** [comment]
I also just read your `package.json` and realized that you expect to pack the electron app with builder just like `pc-nrfconnect-core`.
There will be a difference in the development and the installed app's environment and we haven't actually got to this step in our environment, so this may be broken for a short while, but the idea is that `nrfjprog` directory is not packed in asar package, but copied to the main directory of the electron app.
Regardless where `nrfjprog` directory ends up we'll need to set the correct `LD_LIBRARY_PATH` on Linux and macOS, and on Windows the libraries are simply loaded from the same location where the bindings file is (`node_modules/pc-nrfjprog-js/build/Release`), so they are copied/symlinked there too.

**Comment by baymac** [comment]
Hi @bencefr 
Thanks for the hint how the new bindings are linked together. From your above commands I could verify that it detects the highlevelnrfjprog:

```
```

**Comment by bencefr** [comment]
That output shows that it didn't find the highlevelnrfjprog. If you see a full path after the arrow, you'll be alright.

**Comment by baymac** [comment]
@bencefr sorry my bad :sweat_smile: Do you also suggest I need to make changes in my packaging to be able to make this library compatible? With the workaround as suggested with the LD_LIBRARY_PATH set I see the same issue i.e. `libhighlevelnrfjprog.so: cannot open shared object`.

**Comment by baymac** [comment]
I am sorry again I shared with you the wrong log:
```
linux-vdso.so.1 (0x00007fff88cf2000)
        libhighlevelnrfjprog.so => /home/parichay/Cypherock/cypherock-live-desktop/app/node_modules/pc-nrfjprog-js/nrfjprog/libhighlevelnrfjprog.so (0x00007f42922c0000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f4291f37000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f4291d1f000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f429192e000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f429172a000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f429285e000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f429138c000)
```

**Comment by baymac** [comment]
Currently the app gets compiled successfully but since I am currently away from a NRF device so cannot test it. I think it should work in the development. But while packaging I see `file source doesn't exist from=/home/parichay/Cypherock/cypherock-live-desktop/node_modules/pc-nrfjprog-js/nrfjprog` in the logs and the app doesn't launch. Do you have any leads on this?

**Comment by bencefr** [comment]
I should work on this exact issue for our app next week, so I'll get back here.

**Comment by baymac** [comment]
Thanks would be big help for me. Let me know if I can assist you with
anything.

**Comment by bencefr** [comment]
Hi @baymac ,

Finally we got to this in our environment and you can see the relevant change here:
https://github.com/NordicSemiconductor/pc-nrfconnect-core/blob/release/3.3/index.js#L57-L58

By this change your our bundled app on Linux and macOS will also able to load the highlevel library.
Note that index.js is setting LD_LIBRARY_PATH in electron's main process, which will have no effect in the main process, but all child processes (the renderers) will inherit this value correctly.
